import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import logo from "./../images/logo.png";
import Link from "next/link";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>1kbazzer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.log}>
          <div className={styles.logodiv}>
            <Image src={logo} alt="logo" />
          </div>

          <h2>Welcome Admin</h2>
          <form>
            <div className={styles.inputcont}>
              <input type="text" />
              <label>Username</label>
              <div className={styles.border1}></div>
            </div>
            <div className={styles.inputcont}>
              <input type={styles.password} />
              <label>Password</label>
              <div className={styles.border2}></div>
            </div>

            <div className={styles.clear}></div>

            <div className={styles.loginButtonDiv}>
              <Link href="MainDashboard">
                <input type="submit" value="Sign In" />
              </Link>
            </div>
          </form>
        </div>
      </main>
    </div>
  );
};

export default Home;
