import Head from "next/head";
import { Inter } from "@next/font/google";

const inter = Inter({ subsets: ["latin"] });
import Sidenav from "../components/sidebar/Sidenav";
import LoginPage from "./LoginPage";

export default function Home() {
  return (
    <>
      <Head>
        <title>1k Bazar Admin Panel</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <LoginPage />
      </div>
    </>
  );
}
